/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SpielerRouteImport } from './routes/spieler_/route'
import { Route as SpieleRouteImport } from './routes/spiele_/route'
import { Route as IndexIndexImport } from './routes/_index/index'

// Create/Update Routes

const SpielerRouteRoute = SpielerRouteImport.update({
  id: '/spieler_',
  path: '/spieler',
  getParentRoute: () => rootRoute,
} as any)

const SpieleRouteRoute = SpieleRouteImport.update({
  id: '/spiele_',
  path: '/spiele',
  getParentRoute: () => rootRoute,
} as any)

const IndexIndexRoute = IndexIndexImport.update({
  id: '/_index/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spiele_': {
      id: '/spiele_'
      path: '/spiele'
      fullPath: '/spiele'
      preLoaderRoute: typeof SpieleRouteImport
      parentRoute: typeof rootRoute
    }
    '/spieler_': {
      id: '/spieler_'
      path: '/spieler'
      fullPath: '/spieler'
      preLoaderRoute: typeof SpielerRouteImport
      parentRoute: typeof rootRoute
    }
    '/_index/': {
      id: '/_index/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/spiele': typeof SpieleRouteRoute
  '/spieler': typeof SpielerRouteRoute
  '/': typeof IndexIndexRoute
}

export interface FileRoutesByTo {
  '/spiele': typeof SpieleRouteRoute
  '/spieler': typeof SpielerRouteRoute
  '/': typeof IndexIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/spiele_': typeof SpieleRouteRoute
  '/spieler_': typeof SpielerRouteRoute
  '/_index/': typeof IndexIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/spiele' | '/spieler' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/spiele' | '/spieler' | '/'
  id: '__root__' | '/spiele_' | '/spieler_' | '/_index/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  SpieleRouteRoute: typeof SpieleRouteRoute
  SpielerRouteRoute: typeof SpielerRouteRoute
  IndexIndexRoute: typeof IndexIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  SpieleRouteRoute: SpieleRouteRoute,
  SpielerRouteRoute: SpielerRouteRoute,
  IndexIndexRoute: IndexIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/spiele_",
        "/spieler_",
        "/_index/"
      ]
    },
    "/spiele_": {
      "filePath": "spiele_/route.tsx"
    },
    "/spieler_": {
      "filePath": "spieler_/route.tsx"
    },
    "/_index/": {
      "filePath": "_index/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
