packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  typescript: ~7.0.2

catalogs:
  react:
    '@types/react': ^19.3.0
    '@types/react-dom': ^19.3.0
    react: ^19.3.0
    react-dom: ^19.3.0
  react-libs:
    react-hook-form: ^7.88.0
  validation:
    valibot: ^1.5.0

allowBuilds:
  '@biomejs/biome': true
  '@firebase/util': true
  '@tailwindcss/oxide': true
  esbuild: true
  protobufjs: true
