import {
  collection,
  type DocumentReference,
  doc,
  setDoc,
} from 'firebase/firestore';
import { db } from '../firebase/db';
import type { BaseModel } from '../model/base/model';
import { baseModelConverter } from './base-model-converter';

/**
 * Creates an entity with its explicitly assigned id.
 *
 * @param path
 * @param entity
 */
export const createEntity = async <T extends BaseModel>(
  path: string,
  entity: T,
): Promise<void> => {
  if (!entity.id) {
    throw new Error('Cannot create an entity without an explicit id');
  }

  const entityRef = doc(db, path, entity.id).withConverter(
    baseModelConverter<T>(),
  );
  await setDoc(entityRef, entity);
};

/** Creates an entity with an id generated by Firestore. */
export const createEntityWithGeneratedId = async <T extends BaseModel>(
  path: string,
  entity: Omit<T, 'id'>,
): Promise<T> => {
  const entityRef: DocumentReference<T> = doc(
    collection(db, path),
  ).withConverter(baseModelConverter<T>());

  const createdEntity = { id: entityRef.id, ...entity } as T;
  await setDoc(entityRef, createdEntity);
  return createdEntity;
};
