services:
  backend:
    image: tipprunde
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - 127.0.0.1:2605:2605
